feat: add waiting state for subtasks steps
ovh/utask pull request #331
Opened 2022-04-16 18:33 UTC by rclsilver

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Improve subtasks management.

* **What is the current behavior?** (You can also link to an open issue here)

If a step waiting for a subtask kept in TODO has less "try" than the max tries, the step state is TO_RETRY and resolution running. If step is over, then resolution is BLOCKED.

* **What is the new behavior (if this is a feature change)?**

Resolution will always be WAITING if there is no other failed steps.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No breaking change.

* **Other information**:

2022-04-16 18:36 UTC, ovh-cds commented
CDS Report test#1249.0 ✘  
* tests and lint
  * golangci-lint ✔ 
  * unit-test and integration-tests ✘

2022-05-02 16:52 UTC, rbeuque74 requested changes

2022-05-02 16:52 UTC, rbeuque74 commented on pkg/plugins/builtin/subtask/subtask.go
>  			stepError = errors.NewNotProvisioned(fmt.Errorf("Task %q will start shortly", t.PublicID), "")
```suggestion
			stepError = errors.NewNotAssigned(fmt.Errorf("Task %q will start shortly", t.PublicID), "")
```

2022-05-03 09:11 UTC, rbeuque74 approved these changes

2022-05-04 08:51 UTC, merged