feat: add compress package & the ability to compress steps in a resolution
ovh/utask pull request #368
Opened 2022-10-15 09:51 UTC by orandin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature

* **What is the current behavior?** (You can also link to an open issue here)

The steps aren't compressed.

* **What is the new behavior (if this is a feature change)?**

Now, we can compress the steps in a resolution to reduce the row size in database.
The compression algorithm used is saved in database to ensure backward compatibility in the case where the compression algorithm is changed. 

By default, no compression algorithm is used.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

To compress in `gzip`, update `utask-cfg` to add: 

```json
{
    "steps_compression": "gzip"
}
```

2022-10-15 14:33 UTC, rbeuque74 approved these changes
Thanks, that a nice proposal.
Will run the CI tests on Monday

2022-10-17 08:32 UTC, ovh-cds commented
CDS Report test#1448.0 ✘  
* tests and lint
  * golangci-lint ✔ 
  * unit-test and integration-tests ✘

2022-10-18 12:19 UTC, rclsilver requested changes

2022-10-18 12:19 UTC, rclsilver commented on pkg/compress/compress.go
> +	if ok {
Returning an error when `ok` is `true` is disturbing me. Maybe you could rename to `found` or `exists`?

2022-10-18 12:19 UTC, rclsilver commented on pkg/compress/compress.go
> +func RegisterCompression(name string, c Compression) error {
Maybe `RegisterAlgorithm`?

2022-10-18 12:19 UTC, rclsilver commented on pkg/compress/compress.go
> +		return nil, fmt.Errorf("no compression for type '%s'", name)
%s compression algorithm not found

2022-10-18 12:19 UTC, rclsilver commented on pkg/compress/gzip/gzip.go
> +const CompressionName = "gzip"
AlgorithmName or just Name ?

2022-10-18 12:19 UTC, rclsilver commented on sql/migrations/009_resolution_compression_step.sql
> +ALTER TABLE "resolution" ADD COLUMN "compression_steps" TEXT;
steps_compression_alg

2022-10-18 12:19 UTC, rclsilver commented on utask.go
> +	StepsCompression                           string                   `json:"steps_compression"`
StepsCompressionAlg(orithm)

2022-10-25 07:48 UTC, rclsilver requested changes
Could you fix the version in the schema.sql please?

I made some tests  and I guess that encrypting a gzip version of the json is more efficient:
```
root@939d37decdb7:/go/src/github.com/ovh/utask/cmd/test-compress# go run test-compress.go 
INFO[0000] file: json-1.json: 9581 bytes - gzip(encrypt(json)): 9637 bytes - encrypt(gzip(json)): 2626 bytes 
root@939d37decdb7:/go/src/github.com/ovh/utask/cmd/test-compress# 
```

2022-10-27 23:14 UTC, rbeuque74 commented
Last comment of @rclsilver seems relevant, we will gain more space doing it the other way :+1:

2022-10-28 07:00 UTC, rclsilver approved these changes

2022-10-28 07:15 UTC, ovh-cds commented
CDS Report test#1463.0 ✘  
* tests and lint
  * golangci-lint ✘  
  * unit-test and integration-tests ✔

2022-10-28 07:46 UTC, rclsilver submitted a review, later dismissed

2022-10-28 12:19 UTC, rclsilver approved these changes

2022-11-14 11:47 UTC, rbeuque74 approved these changes

2022-11-14 13:19 UTC, merged