Chore update dependencies / remove tat notification
ovh/utask pull request #514
Opened 2024-03-14 13:47 UTC by fsamin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  * [chore: drop tat notification](https://github.com/ovh/utask/commit/04b2f1592fd627f0af918441f9e093356ec75377)
  * [chore: upgrade yaml lib to sigs.k8s.io/yaml](https://github.com/ovh/utask/commit/703e2face409b25986220371f341dbe6a7ead479)
  * [chore: upgrade to golang 1.22 and node 18](https://github.com/ovh/utask/commit/1b97af3a487bd4542347c50402ae98e574fcb832)

* **What is the current behavior?** (You can also link to an open issue here)
  - n/a

* **What is the new behavior (if this is a feature change)?**
  - n/a

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
   - [chore: drop tat notification](https://github.com/ovh/utask/commit/04b2f1592fd627f0af918441f9e093356ec75377)

* **Other information**:

2024-03-14 14:06 UTC, rclsilver submitted a review, later dismissed

2024-03-14 14:39 UTC, wI2L requested changes
Should also delete the type `NotifyBackendTat`: https://github.com/ovh/utask/blob/464ee0679e155ea844d7f306fb85084219796fc0/utask.go#L172

2024-03-14 14:45 UTC, richardlt submitted a review, later dismissed

2024-03-15 08:09 UTC, ovh-cds commented
CDS Report package#1857.0 ✘  
* Stage 1
  * Docker build ✘

2024-03-15 09:37 UTC, wI2L approved these changes

2024-03-25 08:27 UTC, merged